package flowpayOfferErrors

import "errors"

var (
	ErrMethodNotAllowed    = errors.New("method_not_allowed")
	ErrOfferNotFound       = errors.New("offer_not_found")
	ErrReservationNotFound = errors.New("reservation_not_found")
	ErrInsufficientBalance = errors.New("insufficient_balance")

	ErrOfferCodeRequired                = errors.New("offer_code_missing")
	ErrCreatedByRequired                = errors.New("offer_creator_user_missing")
	ErrOfferTypeRequired                = errors.New("offer_type_missing")
	ErrOfferTypeInvalid                 = errors.New("offer_type_is_invalid")
	ErrCompanyIdRequired                = errors.New("company_id_missing")
	ErrCompanyIdIsInvalid               = errors.New("company_does_not_exist")
	ErrUserNotFound                     = errors.New("user_does_not_exist")
	ErrUserNotInCompany                 = errors.New("user_does_not_belong_in_company")
	ErrOfferAmountOrPercentageRequired  = errors.New("need_offer_amount_or_percentage")
	ErrOfferAmountInvalid               = errors.New("offer_amount_invalid")
	ErrOfferPercentageInvalid           = errors.New("offer_percentage_invalid")
	ErrMaxBenefitAmountInvalid          = errors.New("max_benefit_amount_invalid")
	ErrMaxRedemptionsPerUserInvalid     = errors.New("max_redemptions_per_user_invalid")
	ErrMaxRedemptionsInvalid            = errors.New("max_redemptions_invalid")
	ErrStartTimeRequired                = errors.New("start_time_missing")
	ErrEndTimeRequired                  = errors.New("end_time_missing")
	ErrStartTimeAfterEndTime            = errors.New("start_time_after_end_time")
	ErrAccountIdRequired                = errors.New("account_id_missing")
	ErrPaymentIdRequired                = errors.New("payment_id_missing")
	ErrReservationIdRequired            = errors.New("reservation_id_missing")
	ErrRedemptionIdRequired             = errors.New("redemption_id_missing")
	ErrOfferIdRequired                  = errors.New("offer_id_missing")
	ErrOfferStatusRequired              = errors.New("offer_status_missing")
	ErrOfferStatusInvalid               = errors.New("offer_status_invalid")
	ErrOfferNotActive                   = errors.New("offer_not_active")
	ErrOfferExpired                     = errors.New("offer_expired")
	ErrOfferNotStarted                  = errors.New("offer_not_started")
	ErrOfferRedemptionLimitReached      = errors.New("offer_redemption_reached")
	ErrOfferReservationLimitReached     = errors.New("offer_reservation_reached")
	ErrPaymentAlreadyReserved           = errors.New("offer_already_reserved")
	ErrInvalidRequestBody               = errors.New("invalid request body")
	ErrCreateOfferFailed                = errors.New("failed to create offer")
	ErrReserveOfferFailed               = errors.New("failed to reserve offer")
	ErrRedeemOfferFailed                = errors.New("failed to redeem offer")
	ErrMinimumPaymentAmountNegative     = errors.New("minimum_payment_amount_is_negative")
	ErrMaximumPaymentAmountNegative     = errors.New("maximum_payment_amount_is_negative")
	ErrMinimumPaymentAmountInvalid      = errors.New("minimum_payment_amount_cannot_exceed_maximum")
	ErrReservationAccountMismatch       = errors.New("offer_reserve_account_id_does_not_match")
	ErrReservationPaymentMismatch       = errors.New("offer_reserve_payment_id_does_not_match")
	ErrReservationOfferMismatch         = errors.New("offer_reserve_offer_id_does_not_match")
	ErrReservationExpired               = errors.New("offer_reservation_expired")
	ErrReservationReservationIDMismatch = errors.New("offer_reserve_reservation_id_does_not_match")
	ErrReservationNotReserved           = errors.New("reservation_not_in_reserved_state")

	ErrOfferRequestTimedOut = errors.New("offer request timed out")
	ErrOfferRequestCanceled = errors.New("offer request canceled")

	ErrIdempotencyRequired   = errors.New("idempotency key_is_missing")
	ErrIdempotencyMismatch   = errors.New("idempotency key reused with different payload")
	ErrIdempotencyInProgress = errors.New("Offer is in progress")
)
