package constants

const ServiceName = "reconciliation-service"

const PaymentsWithoutTransactionsCheckName = "payments_without_transactions"
const PaymentsWithInvalidTransactionPairCheckName = "payments_invalid_transaction_pair"
const PaymentsWithoutIdempotencyRowsCheckName = "payments_without_idempotency_rows"
const PaymentsWithIdempotencyPaymentIDMismatchCheckName = "payments_with_idempotency_payment_id_mismatch"
const PaymentsMissingCompletedIdempotencyCheckName = "payments_missing_completed_idempotency"

const IdempotencyCompletedWithoutPaymentCheckName = "idempotency_completed_without_payment"
const IdempotencyMissingPaymentIDCheckName = "idempotency_missing_payment_id"
const IdempotencyDuplicatePaymentIDCheckName = "idempotency_duplicate_payment_id"
const IdempotencyExpiredInProgressCheckName = "idempotency_expired_in_progress"
const IdempotencyInProgressWithoutOutboxCheckName = "idempotency_in_progress_without_outbox"
const IdempotencyOutboxPaymentIDMismatchCheckName = "idempotency_outbox_payment_id_mismatch"
const IdempotencyMultipleOutboxPaymentIDsCheckName = "idempotency_multiple_outbox_payment_ids"

const OutboxStuckProcessingCheckName = "outbox_stuck_processing"
const OutboxFailedRetryExhaustedCheckName = "outbox_failed_retry_exhausted"
const OutboxEligibleBacklogCheckName = "outbox_eligible_backlog"
const OutboxBacklogSummaryCheckName = "outbox_backlog_summary"
const OutboxWithoutIdempotencyRowsCheckName = "outbox_without_idempotency_rows"
const OutboxPublishedWithoutPaymentCheckName = "outbox_published_without_payment"

const TransactionsMissingLedgerSideCheckName = "transactions_missing_ledger_side"
const TransactionsAmountCurrencyImbalanceCheckName = "transactions_amount_currency_imbalance"
const TransactionsWithoutPaymentsCheckName = "transactions_without_payments"
const TransactionsStatusMismatchCheckName = "transactions_status_mismatch"

const OfferSuccessfulPaymentsWithUnredeemedReservationCheckName = "offer_successful_payments_with_unredeemed_reservation"
const OfferRedeemedReservationsWithoutSuccessfulPaymentCheckName = "offer_redeemed_reservations_without_successful_payment"
const OfferReservationsWithoutPaymentCheckName = "offer_reservations_without_payment"
const OfferRedemptionsWithoutPaymentCheckName = "offer_redemptions_without_payment"
const OfferExpiredReservationsStuckReservedCheckName = "offer_expired_reservations_stuck_reserved"
const OfferReservationRedemptionStatusMismatchCheckName = "offer_reservation_redemption_status_mismatch"
const OfferRedeemedCountDriftCheckName = "offer_redeemed_count_drift"
