CREATE DATABASE IF NOT EXISTS payment_db;
CREATE DATABASE IF NOT EXISTS ledger_db;
CREATE DATABASE IF NOT EXISTS wallet_db;
CREATE DATABASE IF NOT EXISTS offer_db;
CREATE DATABASE IF NOT EXISTS fraud_db;
CREATE DATABASE IF NOT EXISTS reconciliation_db;