# ---------- Builder ----------
FROM golang:1.26.5 AS builder

WORKDIR /app

# Cache dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy source
COPY . .

# Build
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build \
    -ldflags="-s -w" \
    -o api-service \
    ./cmd/api

# ---------- Runtime ----------
FROM gcr.io/distroless/static-debian12

WORKDIR /

COPY --from=builder /app/api-service .

EXPOSE 8080

ENTRYPOINT ["/api-service"]