name: "flowpay-infra"

services:

  # ----------------------------
  # 🐘 PostgreSQL
  # ----------------------------
  postgres:
    image: postgres:15
    # container_name: flowpay-postgres
    restart: unless-stopped
    env_file:
      - ./env/postgres.env
    ports:
      - "${POSTGRES_HOST_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # ----------------------------
  # 🔴 Redis
  # ----------------------------
  redis:
    image: redis:7
    # container_name: flowpay-redis
    restart: unless-stopped
    env_file:
      - ./env/redis.env
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5


  # ----------------------------
  # 📨 Kafka
  # ----------------------------
  kafka:
    image: apache/kafka:4.3.1
    # container_name: flowpay-kafka
    restart: unless-stopped

    env_file:
      - ./env/kafka.env
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list >/dev/null 2>&1"
        ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 15s

    ports:
      - "9092:9092"
      - "9094:9094"

    volumes:
      - kafka_data:/var/lib/kafka/data
  
  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    ports:
      - 8080:8080
    env_file:
      - ./env/kafka-ui.env
    depends_on:
      - kafka
      
  kafka-init:
    image: apache/kafka:4.3.1
    depends_on:
      kafka:
        condition: service_started

    volumes:
      - ./kafka/topics.yaml:/config/topics.yaml

    entrypoint:
      - /bin/sh
      - -ec
      - |
        echo "Waiting for Kafka..."

        until /opt/kafka/bin/kafka-topics.sh \
          --bootstrap-server kafka:9092 \
          --list >/dev/null 2>&1
        do
          sleep 2
        done

        echo "Kafka is ready"

        topic_name=""
        partitions=""

        while IFS= read -r line; do
          case "$$line" in
            *"- name:"*)
              topic_name=$$(echo "$$line" | awk -F': ' '{print $$2}')
              ;;
            *"partitions:"*)
              partitions=$$(echo "$$line" | awk -F': ' '{print $$2}')

              if [ -n "$$topic_name" ] && [ -n "$$partitions" ]; then
                echo "Creating topic: $$topic_name"

                /opt/kafka/bin/kafka-topics.sh \
                  --bootstrap-server kafka:9092 \
                  --create \
                  --if-not-exists \
                  --topic "$$topic_name" \
                  --partitions "$$partitions" \
                  --replication-factor 1
              fi
              ;;
          esac
        done < /config/topics.yaml

        echo "Topics ready"
  # ----------------------------
  # 📊 Prometheus
  # ----------------------------
  prometheus:
    image: prom/prometheus:v3.13.1
    # container_name: flowpay-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/rules:/etc/prometheus/rules
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    depends_on:
      - postgres

  # ----------------------------
  # 📈 Grafana
  # ----------------------------
  grafana:
    image: grafana/grafana:11.6.16-ubuntu
    # container_name: flowpay-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - ./env/grafana.env
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards/json
    depends_on:
      - prometheus
      - loki

  # ----------------------------
  # 📜 Loki (Log storage)
  # ----------------------------
  loki:
    image: grafana/loki:3.7.3
    # container_name: flowpay-loki
    restart: unless-stopped
    ports:
      - "3100:3100"
    volumes:
      - ./loki/loki-config.yml:/etc/loki/local-config.yaml
      - loki_data:/loki
    command:
      - "-config.file=/etc/loki/local-config.yaml"

  # ----------------------------
  # 📤 Promtail (Log shipper)
  # ----------------------------
  promtail:
    image: grafana/promtail:3.6.11
    # container_name: flowpay-promtail
    restart: unless-stopped
    volumes:
      - ./promtail/promtail-config.yml:/etc/promtail/config.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ../logs:/var/log/flowpay:ro
      - promtail_positions:/tmp
    command:
      - "-config.file=/etc/promtail/config.yml"
    depends_on:
      - loki

  # ----------------------------
  # 🔍 Jaeger (Tracing)
  # ----------------------------
  # jaeger:
  #   image: jaegertracing/all-in-one:1.76.0
  #   # container_name: flowpay-jaeger
  #   restart: unless-stopped
  #   ports:
  #     - "16686:16686"   # UI
  #     - "6831:6831/udp" # agent
  #     - "4318:4318"     # OTLP HTTP

volumes:
  postgres_data:
  redis_data:
  grafana_data:
  kafka_data:
  loki_data:
  promtail_positions:
  prometheus_data:
