name: "flowpay-services"

services:
  api-gateway:
    build:
      context: ..
      dockerfile: services/api-gateway/Dockerfile

    restart: unless-stopped
    env_file:
      - ./env/api-gateway.env
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  account-service:
    build:
      context: ..
      dockerfile: services/account-service/Dockerfile

    depends_on:
      postgres:
        condition: service_healthy
      # redis:
      #   condition: service_healthy
      kafka:
        condition: service_healthy

    restart: unless-stopped
    env_file:
      - ./env/account-service.env
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8005/accounts/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  payment-service:
    build:
      context: ..
      dockerfile: services/payment-service/Dockerfile

    depends_on:
      postgres:
        condition: service_healthy
      # redis:
      #   condition: service_healthy
      kafka:
        condition: service_healthy

    restart: unless-stopped
    env_file:
      - ./env/payment-service.env
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8001/payments/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  auth-service:
    build:
      context: ..
      dockerfile: services/auth-service/Dockerfile

    depends_on:
      postgres:
        condition: service_healthy

    restart: unless-stopped
    env_file:
      - ./env/auth-service.env
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8007/auth/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  notification-service:
    build:
      context: ..
      dockerfile: services/notification-service/Dockerfile

    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy

    restart: unless-stopped
    env_file:
      - ./env/notification-service.env
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8008/notification/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  offer-service:
    build:
      context: ..
      dockerfile: services/offer-service/Dockerfile

    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy

    restart: unless-stopped
    env_file:
      - ./env/offer-service.env
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8010/offers/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  payment-executor:
    build:
      context: ..
      dockerfile: services/payment-executor/Dockerfile

    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy

    env_file:
      - ./env/payment-executor.env

  reconciliation-service:
    build:
      context: ..
      dockerfile: services/reconciliation-service/Dockerfile

    depends_on:
      postgres:
        condition: service_healthy

    restart: unless-stopped
    env_file:
      - ./env/reconciliation-service.env
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8013/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s